services:
  solar_api:
    image: planetev_solar_platform:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    command:  node server.js  
    ports:
      - "3000:3000"
    restart: always
    env_file: ".env.production"
